version: '3.6'
services:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=store
      - POSTGRES_PASSWORD=store
    ports:
      - 5432:5432
  redis:
    image: redis
    ports:
      - 6379:6379
