version: '3.6'
services:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=store
      - POSTGRES_PASSWORD=store
  redis:
    image: redis
  store_coroutines_challenge:
    build: ../.
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://database:5432/store
      - FLYWAY_URL=jdbc:postgresql://database:5432/store
      - SPRING_REDIS_HOST=redis
    depends_on:
      - database
      - redis
    ports:
    - 1980:1980
