spring:
  application:
    name: store-sync-challenge
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/store
    username: store
    password: store
  jpa:
    show-sql: true
    open-in-view: false
  redis:
    host: localhost
    port: 6379
  cache:
    redis:
      key-prefix: "store-cache:"
      time-to-live: 180000 # milliseconds - 30 min
    type: redis
    cache-names: product, productList, category
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    ignore-missing-migrations: true
    out-of-order: true

feign:
  client:
    config:
      stockClient:
        url: http://localhost:1899
        connectTimeout: 1000
        readTimeout: 1000

resilience4j:
  retry:
    configs:
      default:
        maxRetryAttempts: 3
        waitDuration: 1s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 150s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        registerHealthIndicator: true

server:
  port: 1980