# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: debug
        run: id -u; whoami
      - name: uninstall rootful Docker
        run: sudo apt-get -q -y --purge remove moby-engine moby-buildx && sudo rm -rf /var/run/docker.sock
      - name: install rootless Docker
        run: |
          mkdir -p $XDG_RUNTIME_DIR || true
          curl -fsSL https://get.docker.com/rootless | sh > init.sh
          cat init.sh
          source <(grep '^export' init.sh)
          PATH=$HOME/bin:$PATH dockerd-rootless.sh --experimental --storage-driver vfs &
          sleep 1
          DOCKER_HOST=unix://$XDG_RUNTIME_DIR/docker.sock docker info || ls -la $XDG_RUNTIME_DIR
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
